/**
	This is a file generated by MCP (managed code pattern) approach.
    
    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
export const $UserRepository = Symbol.for("@leight/user/IUserRepository");
export const $UserRepositoryMapper = Symbol.for("@leight/user/IUserRepositoryMapper");
export const $UserRepositoryService = Symbol.for("@leight/user/IUserRepositoryService");
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_rryk6og4d4y2b5naaxnnvj3j = true;