/**
 This is a file generated by MCP (managed code pattern) approach.

 So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
    $FileSource,
    FileQuerySchema,
    type IFileSourceSchema
}                            from "@leight/file";
import {withSourceProcedure} from "@leight/trpc-source-server";

export const FileSourceProcedure = withSourceProcedure<IFileSourceSchema>({
    source: $FileSource,
    schema: FileQuerySchema,
});
