/**
	This is a file generated by MCP (managed code pattern) approach.

    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IContainer}              from "@leight/container";
import {
    $KeywordRepository,
    $KeywordRepositoryMapper,
    $KeywordRepositoryService
}                                     from "@leight/keyword";
import {BaseKeywordRepositoryMapper}  from "../mapper/BaseKeywordRepositoryMapper";
import {BaseKeywordRepositoryEx}      from "../repository/BaseKeywordRepositoryEx";
import {BaseKeywordRepositoryService} from "../service/BaseKeywordRepositoryService";

export const withKeywordRepositoryContainer = (container: IContainer) => {
    container.bindClass($KeywordRepository, BaseKeywordRepositoryEx);
    container.bindClass($KeywordRepositoryMapper, BaseKeywordRepositoryMapper);
    container.bindClass($KeywordRepositoryService, BaseKeywordRepositoryService);
};
/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_ni6iwhl5p3qrhev8nzr2pf09 = true;
