/**
 This is a file generated by MCP (managed code pattern) approach.

 So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {
    FileSchema,
    type IFileSourceSchema,
    type IUseFileCountQuery,
    type IUseFileQuery
}                from "@leight/file";
import {
    type IQueryProviderProps,
    QueryProvider
}                from "@leight/query-client";
import {
    type ISourceProps,
    Source
}                from "@leight/source-client";
import {type FC} from "react";
import {
    FileProvider,
    FileSortProvider,
    useFileSort
}                from "./ClientStore";

export interface IFileSourceProps extends ISourceProps<IFileSourceSchema> {
    useSourceQuery: IUseFileQuery;
}

export interface IFileQueryProviderProps extends IQueryProviderProps<IFileSourceSchema> {
    useCountQuery: IUseFileCountQuery;
}

export const FileSource: FC<IFileSourceProps>               = props => {
    return <Source<IFileSourceSchema>
        schema={FileSchema}
        SourceProvider={FileProvider}
        useSortState={useFileSort}
        {...props}
    />;
};
export const FileQueryProvider: FC<IFileQueryProviderProps> = props => {
    return <QueryProvider<IFileSourceSchema>
        SortProvider={FileSortProvider}
        {...props}
    />;
};
