import {useOptionalFormItemContext} from "@leight-core/viv";
import {
    Input as CoolInput,
    InputProps
}                                   from "antd";
import {
    FC,
    forwardRef
}                                   from "react";

export interface IInputProps extends Partial<InputProps> {
    /**
     * Use placeholder generated by parent FormItem.
     */
    usePlaceholder?: boolean;
}

export const Input: FC<IInputProps> = forwardRef(({usePlaceholder, ...props}, ref) => {
    const formItemContext = useOptionalFormItemContext();
    formItemContext && usePlaceholder && (props.placeholder = formItemContext.label);
    return <CoolInput ref={ref as any} {...props}/>;
});
