import {Input as CoolInput, InputProps} from "antd";
import {FC, forwardRef} from "react";
import {useOptionalFormItemContext} from "../FormItemContext";

export interface IInputProps extends Partial<InputProps> {
	/**
	 * Use placeholder generated by parent FormItem.
	 */
	usePlaceholder?: boolean;
}

export const Input: FC<IInputProps> = forwardRef(({usePlaceholder, ...props}, ref) => {
	const formItemContext = useOptionalFormItemContext();
	return <CoolInput
		ref={ref as any}
		placeholder={formItemContext && usePlaceholder ? formItemContext.label : props.placeholder}
		{...props}
	/>;
});
