/**
	This is a file generated by MCP (managed code pattern) approach.

    So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type FilterSource}        from "@leight/filter";
import {AbstractRepositoryMapper} from "@leight/source-server";

export class BaseFilterRepositoryMapper extends AbstractRepositoryMapper<FilterSource["Schema"]["Mapper"]> {
}

/**
 * Default export marking a file it's generated and also preventing failing
 * an empty file export (every module "must" have an export).
 */
export const $leight_hl9hkahw06jplzhj4jamnwbf = true;
