/**
 This is a file generated by MCP (managed code pattern) approach.

 So, please, DO NOT modify this file as it would get re-generated and you would be f*cked up.
 */
import {type IJobSource} from "@leight/job";
import {JobBaseSource}   from "./ServerBaseSource";

export class JobSource extends JobBaseSource implements IJobSource {
}
